In [6]:
import numpy as np

In [3]:
x = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]])
print(x)
print(x[3][1])
print(x[1])

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
8
[3 4]


In [4]:
a = np.zeros(10)
b = np.ones(10)
c = np.full(10, 5)
d = np.arange(10, 20)
print(a, "\n", b, "\n", c, "\n", d)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 
 [5 5 5 5 5 5 5 5 5 5] 
 [10 11 12 13 14 15 16 17 18 19]


In [5]:
z = np.random.random((10, 10))
zmin, zmax, zmean = z.min(), z.max(), z.mean()
print(zmin, zmax, zmean)

0.0010777633701953837 0.987733077765435 0.493285282709371


In [6]:
a = np.arange(25).reshape(5, 5)
a[[0,1]] = a[[1,0]]
print(a)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [8]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print( 0.3 == 3 * 0.1)

nan
False
False
nan
False


In [9]:
arr = np.array([5, 4, 7, 3, 1, 2, 9, 0])
print(np.sort(arr))

[0 1 2 3 4 5 7 9]


In [8]:
m = np.zeros((8, 8), dtype = int)
m[1::2,::2] = 1
m[::2,1::2] = 1
print(m)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [9]:
m = np.zeros((5,5), dtype = int)
m += np.arange(5)
print(m)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [10]:
lst = np.random.random((3,3,3))
print(lst)

[[[0.11615812 0.99993768 0.82342145]
  [0.8735031  0.95857227 0.837914  ]
  [0.48343489 0.85219463 0.85337907]]

 [[0.75226499 0.57554178 0.41145068]
  [0.7729943  0.23841912 0.21413772]
  [0.83938918 0.03642134 0.62867399]]

 [[0.01560652 0.59182148 0.01068334]
  [0.27934331 0.37587614 0.71620844]
  [0.86761232 0.14741598 0.18637136]]]


In [11]:
a = int(input())
m = np.zeros((a,a), dtype = int)
print(m)
a = a - 1
m[0] = 1
m[1:a,0] = 1
m[1:a, -1] = 1
m[a] = 1
print(m)


6
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[1 1 1 1 1 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 0 0 0 0 1]
 [1 1 1 1 1 1]]


In [12]:
arr = np.array([7, 3, 9, 4, 8, 1, 5, 0, 6])
arr2 = np.sort(arr)[::-1] 
print(arr2)

[9 8 7 6 5 4 3 1 0]


In [13]:
m = np.zeros((8, 8), dtype = int)
print(m.shape)
print(m.size)
print(m.ndim)

(8, 8)
64
2


In [13]:
import pandas as pd
lst = [1, 2, 3, 4, 5]
d = {'a':1, 'b':2, 'c':3}
ndarr = np.array([1, 2, 3, 4, 5])

s1 = pd.Series(lst)
s2 = pd.Series(d)
s3 = pd.Series(ndarr, ['a', 'b', 'c', 'd', 'e'])

print(s1)
print(s2)
print(s3)

0    1
1    2
2    3
3    4
4    5
dtype: int64
a    1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int32


In [14]:
s1 = pd.Series([1, 2, 3, 4, 5], ['a', 'b', 'c', 'd', 'e'])
s2 = pd.Series([5, 4, 3, 2, 1])
print(s1['a'])
print(s2[0])
print(s2[3:])

1
5
3    2
4    1
dtype: int64


In [15]:
dataframe = pd.DataFrame()
dataframe['Имя'] = ['Галуаев Максим', 'Стивен Стивенсон']
dataframe['Возраст'] = [18, 35]
dataframe['Водитель'] = [False, True]
dataframe

Имя  Возраст  Водитель
0    Галуаев Максим       18     False
1  Стивен Стивенсон       35      True

In [7]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(5)

Name PClass    Age     Sex  \
0                   Allen, Miss Elisabeth Walton    1st  29.00  female   
1                    Allison, Miss Helen Loraine    1st   2.00  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                  Allison, Master Hudson Trevor    1st   0.92    male   

   Survived  SexCode  
0         1        1  
1         0        1  
2         0        0  
3         0        1  
4         1        0

In [8]:
url = 'https://raw.githubusercontent.com/chrisalbon/simulated_datasets/master/titanic.csv'
dataframe = pd.read_csv(url)
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()
dataframe

Name PClass    Age     Sex  \
0                      Allen, Miss Elisabeth Walton    1st  29.00  female   
1                       Allison, Miss Helen Loraine    1st   2.00  female   
2               Allison, Mr Hudson Joshua Creighton    1st  30.00    male   
3     Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.00  female   
4                     Allison, Master Hudson Trevor    1st   0.92    male   
...                                             ...    ...    ...     ...   
1308                             Zakarian, Mr Artun    3rd  27.00    male   
1309                         Zakarian, Mr Maprieder    3rd  26.00    male   
1310                               Zenni, Mr Philip    3rd  22.00    male   
1311                               Lievens, Mr Rene    3rd  24.00    male   
1312                                 Zimmerman, Leo    3rd  29.00    male   

      Survived  SexCode  
0            1        1  
1            0        1  
2            0        0  
3            0        1  
4            1        0  
...        ...      ...  
1308         0        0  
1309         0        0  
1310         0        0  
1311         0        0  
1312         0        0  

[1313 rows x 6 columns]

In [9]:
dataframe.iloc[1:4]

Name PClass   Age     Sex  \
1                    Allison, Miss Helen Loraine    1st   2.0  female   
2            Allison, Mr Hudson Joshua Creighton    1st  30.0    male   
3  Allison, Mrs Hudson JC (Bessie Waldo Daniels)    1st  25.0  female   

   Survived  SexCode  
1         0        1  
2         0        0  
3         0        1

In [10]:
dataframe[dataframe['PClass'] == '1st'].head(2)

Name PClass   Age     Sex  Survived  SexCode
0  Allen, Miss Elisabeth Walton    1st  29.0  female         1        1
1   Allison, Miss Helen Loraine    1st   2.0  female         0        1

In [11]:
import numpy as np
a = pd.Series([5, 7, 9, 0, 10, 3])
b = pd.Series([1, 3, 5, 7, 4, 5])
c = sum((a - b)**2)**0.5
print (c)

11.704699910719626


In [21]:
import pandas as pd
url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'
dataframe = pd.read_csv(url)
dataframe

age         workclass  education_num      marital_status  \
0       39         State-gov             13       Never-married   
1       50  Self-emp-not-inc             13  Married-civ-spouse   
2       38           Private              9            Divorced   
3       53           Private              7  Married-civ-spouse   
4       28           Private             13  Married-civ-spouse   
...    ...               ...            ...                 ...   
45217   33           Private             13       Never-married   
45218   39           Private             13            Divorced   
45219   38           Private             13  Married-civ-spouse   
45220   44           Private             13            Divorced   
45221   35      Self-emp-inc             13  Married-civ-spouse   

              occupation   relationship   race  gender  hours_per_week  \
0           Adm-clerical  Not-in-family  White    Male              40   
1        Exec-managerial        Husband  White    Male              13   
2      Handlers-cleaners  Not-in-family  White    Male              40   
3      Handlers-cleaners        Husband  Other    Male              40   
4         Prof-specialty           Wife  Other  Female              40   
...                  ...            ...    ...     ...             ...   
45217     Prof-specialty      Own-child  White    Male              40   
45218     Prof-specialty  Not-in-family  White  Female              36   
45219     Prof-specialty        Husband  White    Male              50   
45220       Adm-clerical      Own-child  Other    Male              40   
45221    Exec-managerial        Husband  White    Male              60   

      native_country  capital income_status  
0      United-States     2174         <=50K  
1      United-States        0         <=50K  
2      United-States        0         <=50K  
3      United-States        0         <=50K  
4              Other        0         <=50K  
...              ...      ...           ...  
45217  United-States        0         <=50K  
45218  United-States        0         <=50K  
45219  United-States        0         <=50K  
45220  United-States     5455         <=50K  
45221  United-States        0          >50K  

[45222 rows x 12 columns]

In [22]:
url = 'https://raw.githubusercontent.com/akmand/datasets/main/adult.csv'
dataframe = pd.read_csv(url)
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()

age  education_num  hours_per_week       capital
count  45222.000000   45222.000000    45222.000000  45222.000000
mean      38.547941      10.118460       40.938017   1012.834925
std       13.217870       2.552881       12.007508   7530.315380
min       17.000000       1.000000        1.000000  -4356.000000
25%       28.000000       9.000000       40.000000      0.000000
50%       37.000000      10.000000       40.000000      0.000000
75%       47.000000      13.000000       45.000000      0.000000
max       90.000000      16.000000       99.000000  99999.000000

In [19]:
dataframe.iloc[1:4]

age         workclass  education_num      marital_status  \
1   50  Self-emp-not-inc             13  Married-civ-spouse   
2   38           Private              9            Divorced   
3   53           Private              7  Married-civ-spouse   

          occupation   relationship   race gender  hours_per_week  \
1    Exec-managerial        Husband  White   Male              13   
2  Handlers-cleaners  Not-in-family  White   Male              40   
3  Handlers-cleaners        Husband  Other   Male              40   

  native_country  capital income_status  
1  United-States        0         <=50K  
2  United-States        0         <=50K  
3  United-States        0         <=50K

In [23]:
dataframe[dataframe['age'] < 30].head(10)

age         workclass  education_num      marital_status  \
4    28           Private             13  Married-civ-spouse   
12   23           Private             13       Never-married   
15   25  Self-emp-not-inc              9       Never-married   
25   19           Private              9       Never-married   
28   23         Local-gov             12       Never-married   
29   20           Private             10       Never-married   
32   22         State-gov             10  Married-civ-spouse   
34   21           Private             10       Never-married   
35   19           Private              9   Married-AF-spouse   
39   24           Private             13  Married-civ-spouse   

           occupation   relationship   race  gender  hours_per_week  \
4      Prof-specialty           Wife  Other  Female              40   
12       Adm-clerical      Own-child  White  Female              30   
15    Farming-fishing      Own-child  White    Male              35   
25       Craft-repair      Own-child  White    Male              40   
28    Protective-serv  Not-in-family  White    Male              52   
29              Sales      Own-child  Other    Male              44   
32      Other-service        Husband  Other    Male              15   
34  Machine-op-inspct      Own-child  White    Male              40   
35       Adm-clerical           Wife  White  Female              25   
39       Tech-support        Husband  White    Male              50   

   native_country  capital income_status  
4           Other        0         <=50K  
12  United-States        0         <=50K  
15  United-States        0         <=50K  
25  United-States        0         <=50K  
28  United-States        0         <=50K  
29  United-States        0         <=50K  
32  United-States        0         <=50K  
34  United-States        0         <=50K  
35  United-States        0         <=50K  
39  United-States        0         <=50K

In [24]:
import numpy as np
from sklearn import preprocessing

feature = np.array([[-500.5], [-100.1], [0], [100.1], [900.9]])
minmax_scale = preprocessing.MinMaxScaler(feature_range = (0, 1))
scaled_feature = minmax_scale.fit_transform(feature)

scaled_feature

array([[0.        ],
       [0.28571429],
       [0.35714286],
       [0.42857143],
       [1.        ]])

In [25]:
x = np.array([[-1000.1], [-200.2], [500.5], [600.6], [9000.9]])
scaler = preprocessing.StandardScaler()
standardized = scaler.fit_transform(x)
standardized

print("Среднее: ", round(standardized.mean()))
print("Стандартное отклонение: ", (standardized.std()))

Среднее:  0
Стандартное отклонение:  1.0


In [27]:
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
dfTest = pd.DataFrame({'A':[14.00,90.20,90.95,96.27,91.21],
                       'B':[103.02,107.26,110.35,114.23,114.68],
                       'C':['big', 'small', 'big', 'small', 'small']})
dfTest[['A', 'B']] = scaler.fit_transform(dfTest[['A', 'B']])
dfTest

A         B      C
0  0.000000  0.000000    big
1  0.926219  0.363636  small
2  0.935335  0.628645    big
3  1.000000  0.961407  small
4  0.938495  1.000000  small

In [28]:
import numpy as np
from sklearn import preprocessing as pr
url = 'https://raw.githubusercontent.com/akmand/datasets/master/iris.csv'
dataframe = pd.read_csv(url)
scaler = pr.MinMaxScaler()
scaler2 = pr.StandardScaler()

dataframe[['sepal_length_cm']] = scaler.fit_transform(dataframe[['sepal_length_cm']]) #нормализация минимаксная
dataframe[['sepal_width_cm']] = scaler2.fit_transform(dataframe[['sepal_width_cm']]) #нормализация z-scaler
dataframe

sepal_length_cm  sepal_width_cm  petal_length_cm  petal_width_cm  \
0           0.222222        1.032057              1.4             0.2   
1           0.166667       -0.124958              1.4             0.2   
2           0.111111        0.337848              1.3             0.2   
3           0.083333        0.106445              1.5             0.2   
4           0.194444        1.263460              1.4             0.2   
..               ...             ...              ...             ...   
145         0.666667       -0.124958              5.2             2.3   
146         0.555556       -1.281972              5.0             1.9   
147         0.611111       -0.124958              5.2             2.0   
148         0.527778        0.800654              5.4             2.3   
149         0.444444       -0.124958              5.1             1.8   

       species  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]